Fix config

diff --git a/kubernetes/src/Makefile b/kubernetes/src/Makefile
--- a/kubernetes/src/Makefile
+++ b/kubernetes/src/Makefile
@@ -45,25 +45,25 @@ setup:
 		IMG=$$(docker image ls -f reference="ptx-edge/$${img}*" --format='{{.Repository}}:{{.Tag}}' | sort | head -n1); \
 		# LOCAL_IMG="localhost:5000/$${IMG}"; \
 		# docker tag $${IMG} $${LOCAL_IMG} && docker push $${LOCAL_IMG} && docker rmi $${LOCAL_IMG}; \
-		if [ -z "$${IMG+x}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
+		if [ -z "$${IMG}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
 		echo "$${IMG} --> ${K3D_REG}/$${IMG}"; \
 		skopeo copy --dest-cert-dir=${CA_DIR} --dest-creds=${REG_CREDS} docker-daemon:$${IMG} docker://${K3D_REG}/$${IMG}; \
 	done
 	for img in ${PTX_CORE}; do \
 		IMG=$$(docker image ls -f reference="ptx-sandbox/$${img}*" --format='{{.Repository}}:{{.Tag}}' | sort | head -n1); \
-		if [ -z "$${IMG+x}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
+		if [ -z "$${IMG}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
 		echo "$${IMG} --> ${K3D_REG}/$${IMG}"; \
 		skopeo copy --dest-cert-dir=${CA_DIR} --dest-creds=${REG_CREDS} docker-daemon:$${IMG} docker://${K3D_REG}/$${IMG}; \
 	done
 	for img in ${CONNECTOR}; do \
 		IMG=$$(docker image ls -f reference="ptx/$${img}*" --format='{{.Repository}}:{{.Tag}}' | sort | head -n1); \
-		if [ -z "$${IMG+x}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
+		if [ -z "$${IMG}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
 		echo "$${IMG} --> ${K3D_REG}/$${IMG}"; \
 		skopeo copy --dest-cert-dir=${CA_DIR} --dest-creds=${REG_CREDS} docker-daemon:$${IMG} docker://${K3D_REG}/$${IMG}; \
 	done
 	for img in ${SAMPLES}; do \
 		IMG=$$(docker image ls -f reference="samples/$${img}*" --format='{{.Repository}}:{{.Tag}}' | sort | head -n1); \
-		if [ -z "$${IMG+x}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
+		if [ -z "$${IMG}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
 		echo "$${IMG} --> ${K3D_REG}/$${IMG}"; \
 		skopeo copy --dest-cert-dir=${CA_DIR} --dest-creds=${REG_CREDS} docker-daemon:$${IMG} docker://${K3D_REG}/$${IMG}; \
 	done
@@ -72,7 +72,7 @@ setup:
 		# IMG=$$(docker image ls -f reference="$${img}*" --format='{{.Repository}}:{{.Tag}}'); \
 		# LOCAL_IMG="localhost:5000/$${IMG}"; \
 		# docker tag $${IMG} $${LOCAL_IMG} && docker push $${LOCAL_IMG} && docker rmi $${LOCAL_IMG}; \
-		if [ -z "$${img+x}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
+		if [ -z "$${img}" ]; then echo "Missing image: $${img}" && exit 1; fi; \
 		echo "$${img} --> ${K3D_REG}/$${img}"; \
 		skopeo copy --dest-cert-dir=${CA_DIR} --dest-creds=${REG_CREDS} docker://$${img} docker://${K3D_REG}/$${img}; \
 	done
